// En trygg minut – helt anonym, inga inloggningar.
// Barnet väljer ingen kategori. Varje tryck ger nästa kategori i ordning.
// Efter 5 tryck (en “runda”) går det vidare till nästa mening i varje kategori.

const categories = [
  [
  "Ingen är perfekt. Du lär dig och det är helt okej.",
  "Det är okej att göra misstag.",
  "Det är okej att öva.",
  "Du gör framsteg, även om det inte känns så.",
  "Det är okej att fråga om hjälp.",
  "Du är modig som fortsätter.",
  "Du är viktig.",
  "Det är okej att vara ny på något.",
  "Alla börjar någonstans.",
  "Du är okej precis här och nu.",
  "Du gör framsteg, även små räknas.",
  "Du är värd respekt.",
  "Det är okej att vara annorlunda.",
  "Det är okej att inte orka ibland.",
  "Det är okej att vara osäker.",
  "Du gör framsteg på ditt sätt.",
  "Du behöver inte vara perfekt.",
  "Du är värd vänlighet, även från dig själv.",
  "Alla lär sig på olika sätt.",
  "Du är okej även när det inte går som du vill.",
  "Du är okej även när allt inte känns bra.",
  "Du behöver inte vara perfekt för att duga.",
  "Du är viktig som du är.",
  "Du duger även när du tvivlar.",
  "Du behöver inte jämföra dig med andra.",
  "Du är okej även när du känner dig liten.",
  "Det är okej att ta ett steg i taget.",
  "Det är okej att behöva hjälp.",
  "Du är inte fel för att det känns svårt.",
  "Du är okej även när du känner så.",
  "Du lär dig genom att försöka.",
  "Det är okej att vara mänsklig.",
  "Du är inte ensam.",
  "Du är värdefull.",
  "Du är tillräcklig även idag.",
  "Du gör ditt bästa.",
  "Det är okej att inte veta ännu.",
  "Du behöver inte skynda.",
  "Du lär dig varje dag.",
  "Du är tillräcklig precis nu.",
  "Du är okej även när du inte känner dig stark.",
  "Du är okej även när du känner dig osynlig.",
  "Det är okej att känna sig annorlunda.",
  "Du är okej även när ingen ser.",
  "Det är okej att känna sig tom.",
  "Det är okej att dra sig undan ibland.",
  "Du är okej även när dagen är grå.",
  "Du behöver inte bestämma allt nu.",
  "Det är okej att känna sig för mycket.",
  "Det är okej att vara mjuk.",
  "Det är okej att inte vara redo.",
  "Det är okej att känna sig osäker inför nytt.",
  "Det är okej att inte vara redo än.",
  "Det är okej att lyssna på dig själv.",
  "Det är okej att känna sig trött i huvudet.",
  "Det är okej att låta saker vänta.",
  "Det är okej att känna sig osedd ibland.",
  "Du duger även med dina behov.",
  "Det är okej att känna sig vilsen ibland.",
  "Det är okej att känna sig på väg.",
  "Du klarar mer än du tror.",
  "Du blir bättre för varje försök.",
  "Du kan ta nästa steg.",
  "Du är duktig på mer än du tror.",
  "Du kan klara svåra saker.",
  "Du har förmågan att fortsätta.",
  "Du kan bygga upp din trygghet.",
  "Du kan lyckas på ditt sätt.",
  "Du har inre styrka.",
  "Du kan ta en ny chans.",
  "Du har redan börjat bygga något bra.",
  "Du är stark även när det känns svårt.",
  "Du kan ta nästa försök.",
  "Du är kapabel att klara utmaningar.",
  "Du kan fortsätta även när det är jobbigt.",
  "Du är på väg att bli tryggare i dig själv.",
  "Du kan bli bättre med tid och övning.",
  "Du har kraft att stå kvar.",
  "Du kan ta dagen som den kommer.",
  "Du har viljan att ta dig framåt.",
  "Du kan klara nästa steg.",
  "Du klarar mer än du tror.",
  "Du har styrka inom dig.",
  "Du ger inte upp, och det är bra.",
  "Du har redan kommit en bit.",
  "Du kan göra små framsteg.",
  "Du kan hitta mod inom dig.",
  "Du har kraft att fortsätta.",
  "Du kan hantera det som är svårt.",
  "Du är på väg att bli tryggare.",
  "Du kan möta en ny dag.",
  "Du har kraft att gå vidare.",
  "Du kan känna hopp.",
  "Du är stark även när det känns jobbigt.",
  "Du kan ta dig igenom detta.",
  "Du är kapabel att klara det här.",
  "Du kan möta det som kommer.",
  "Du har viljan som behövs.",
  "Du kan ta en dag i taget.",
  "Du är på väg framåt."
],
  [
  "Du gör så gott du kan, och det räcker just nu.",
  "Du blir bättre varje gång du försöker.",
  "Du lär dig något nytt varje dag.",
  "Det är okej att känna sig osäker ibland.",
  "Du växer när du vågar försöka.",
  "Du gör ditt bästa just nu.",
  "Det är okej att känna sig trött.",
  "Du blir starkare av att försöka igen.",
  "Du utvecklas mer än du tror.",
  "Du kan bli bättre, steg för steg.",
  "Du lär dig något varje gång du provar.",
  "Det är okej att börja om.",
  "Du är unik på ditt sätt.",
  "Du är inte svag för att du kämpar.",
  "Du lär dig genom att försöka.",
  "Det är okej att vara nybörjare.",
  "Du är mer än det du presterar.",
  "Det är okej att känna sig förvirrad.",
  "Du är inte efter, du är på väg.",
  "Du är värd tålamod.",
  "Det är okej att lära sig långsamt.",
  "Alla kämpar med något.",
  "Det är okej att ta pauser när du behöver.",
  "Du växer när du lär dig.",
  "Det är okej att vara där du är.",
  "Du blir bättre varje gång du provar.",
  "Du lär dig hela tiden.",
  "Du är värd att bli lyssnad på.",
  "Det är okej att ta sin tid.",
  "Du behöver inte stressa.",
  "Det är okej att inte lyckas direkt.",
  "Du är okej även när du tvivlar på dig själv.",
  "Det är okej att känna mycket.",
  "Du gör framsteg, steg för steg.",
  "Det är okej att känna sig förvirrad.",
  "Det är okej att växa långsamt.",
  "Du är okej även när du tvekar.",
  "Du är värd att må bra.",
  "Det är okej att känna sig osäker ibland.",
  "Det är okej att ta en dag i taget.",
  "Det är okej att inte ha energi hela tiden.",
  "Du behöver inte vara snabb för att vara bra.",
  "Du behöver inte passa in för att duga.",
  "Det är okej att känna sig liten ibland.",
  "Du är okej även när orden saknas.",
  "Du behöver inte le hela tiden.",
  "Det är okej att ha blandade känslor.",
  "Du är okej även mitt i tankarna.",
  "Du är okej även när känslorna tar plats.",
  "Du är okej även när du bryr dig mycket.",
  "Du är okej även när du väntar.",
  "Du är okej även innan du försöker.",
  "Du är okej även när du samlar mod.",
  "Du är okej även när du säger nej.",
  "Du är okej även när tankarna snurrar.",
  "Du är okej även när allt inte är klart.",
  "Du är okej även när ingen frågar.",
  "Du är okej även när du hoppas.",
  "Du är okej även utan karta.",
  "Du är okej även när riktningen ändras.",
  "Du är starkare än du känner just nu.",
  "Du har mod i dig.",
  "Du är på väg framåt.",
  "Du kan utvecklas.",
  "Du har styrka även på jobbiga dagar.",
  "Du är mer redo än du tror.",
  "Du är på rätt väg för dig.",
  "Du har redan gjort något bra.",
  "Du kan träna och bli säkrare.",
  "Du är stark i ditt eget tempo.",
  "Du kan klara detta, en bit i taget.",
  "Du kan hitta ditt sätt.",
  "Du är redo att lära mer.",
  "Du kan skapa framsteg.",
  "Du är starkare för varje dag.",
  "Du kan göra framsteg.",
  "Du är kapabel till förändring.",
  "Du kan bygga något bra av detta.",
  "Du är redo att lära mer om dig själv.",
  "Du kan klara nästa steg.",
  "Du gör redan ditt bästa.",
  "Du är på väg framåt.",
  "Du kan ta ett steg i taget.",
  "Du kan fortsätta även när det känns svårt.",
  "Du kan fortsätta i din egen takt.",
  "Du är på rätt väg för dig.",
  "Du är kapabel att lära dig.",
  "Du kan känna stolthet över dig själv.",
  "Du har styrka även idag.",
  "Du kan klara mer än igår.",
  "Du har viljan att fortsätta.",
  "Du kan bli tryggare steg för steg.",
  "Du är på väg mot något bra.",
  "Du kan utvecklas.",
  "Du har styrka inom dig.",
  "Du kan växa av det som händer.",
  "Du har redan visat mod.",
  "Du kan fortsätta även imorgon.",
  "Du är stark även idag.",
  "Du kan känna dig tryggare med tiden."
],
  [
  "Det är okej att inte kunna allt på en gång.",
  "Du duger precis som du är.",
  "Det är okej att ta pauser.",
  "Du behöver inte vara perfekt för att vara bra.",
  "Alla misslyckas ibland.",
  "Det räcker att du är du.",
  "Du behöver inte jämföra dig med andra.",
  "Du är mer än dina misstag.",
  "Det är okej att känna sig ledsen ibland.",
  "Ingen är perfekt, och det behöver du inte vara.",
  "Det är okej att inte lyckas direkt.",
  "Du behöver inte skynda.",
  "Alla lär sig genom att göra fel.",
  "Du blir bättre med tiden.",
  "Du är viktig även när du tvivlar.",
  "Du är okej som du är.",
  "Det är okej att behöva tid.",
  "Du klarar detta i din takt.",
  "Det är okej att vara där du är.",
  "Du gör så gott du kan.",
  "Du gör framsteg, även när du inte märker det.",
  "Du är okej även när det är svårt.",
  "Du gör så gott du kan just nu.",
  "Det är okej att vara osäker ibland.",
  "Du gör ditt bästa, och det räcker.",
  "Det är okej att vara ny på något.",
  "Du är okej även när det känns rörigt.",
  "Du klarar mer än du tror.",
  "Du gör framsteg i din takt.",
  "Du är modig som fortsätter.",
  "Du är okej även när det inte går som du vill.",
  "Du gör så gott du kan.",
  "Du är okej även när känslorna är stora.",
  "Det är okej att vara annorlunda.",
  "Du lär dig hela tiden.",
  "Du är okej även när det tar tid.",
  "Du blir bättre med tiden.",
  "Det är okej att ta små steg.",
  "Du är okej även när det känns tungt.",
  "Du är okej även när du gör fel.",
  "Du lär dig även när det känns som paus.",
  "Det är okej att stanna upp.",
  "Du är okej även när du känner dig utanför.",
  "Du är värdefull utan att visa något.",
  "Det är okej att vila hjärnan.",
  "Du är okej även utan ett svar.",
  "Du lär dig känna dig själv.",
  "Det är okej att ta en sak i taget.",
  "Det är okej att känna sig känslig.",
  "Det är okej att känna djupt.",
  "Det är okej att ta tid på sig.",
  "Det är okej att ta ett djupt andetag.",
  "Det är okej att vänta tills det känns rätt.",
  "Det är okej att sätta gränser.",
  "Det är okej att ta en mental paus.",
  "Det är okej att ta dagen som den kommer.",
  "Det är okej att vilja bli sedd.",
  "Det är okej att vilja höra till.",
  "Det är okej att inte veta vart än.",
  "Du duger även när du provar nytt.",
  "Du har redan kommit långt.",
  "Du kan lära dig nya saker.",
  "Du har redan börjat, och det räknas.",
  "Du har potential.",
  "Du kan öva och bli säkrare.",
  "Du kan ta det här steget.",
  "Du kan bli bättre, steg för steg.",
  "Du kan fortsätta framåt.",
  "Du är modigare än du tror.",
  "Du kan lära dig att lita på dig själv.",
  "Du är uthållig.",
  "Du är på rätt spår.",
  "Du kan bygga självförtroende.",
  "Du är på väg mot något bra.",
  "Du kan lära dig hantera det som är svårt.",
  "Du är stark på ditt eget sätt.",
  "Du kan känna stolthet över att du försöker.",
  "Du är stark även när det känns tungt.",
  "Du kan utveckla nya styrkor.",
  "Du är stark nog att fortsätta.",
  "Du blir starkare när du fortsätter.",
  "Du kan ta det lugnt och fortsätta.",
  "Du är bra som du är.",
  "Du lär dig av det du gör.",
  "Du är inte dålig för att det är svårt.",
  "Du kan klara detta steg.",
  "Du kan fortsätta även långsamt.",
  "Du klarar mer för varje dag.",
  "Du kan ta nästa lilla steg.",
  "Du gör framsteg, även små.",
  "Du kan bygga styrka över tid.",
  "Du är kapabel.",
  "Du kan fortsätta även när det känns tungt.",
  "Du har förmåga att lära dig.",
  "Du kan fortsätta idag också.",
  "Du har kraft att fortsätta.",
  "Du kan bygga trygghet med tiden.",
  "Du är kapabel att växa.",
  "Du kan fortsätta lära dig.",
  "Du är modig."
],
  [
  "Du är okej, även när det känns svårt.",
  "Ingen kan allt, och det är helt normalt.",
  "Du är värdefull även när du tvivlar.",
  "Små steg räknas också.",
  "Du lär dig av det som blir fel.",
  "Ingen förväntar sig att du ska kunna allt.",
  "Du har din egen resa.",
  "Du är värd att må bra.",
  "Du är inte konstig för att du känner så.",
  "Du duger även när det är svårt.",
  "Du är tillräcklig även idag.",
  "Du är okej även när du tvekar.",
  "Du behöver inte vara bäst.",
  "Du är okej även när det tar tid.",
  "Du duger precis nu.",
  "Du växer varje dag.",
  "Du är okej även när du lär dig.",
  "Du duger även när det känns rörigt.",
  "Du är tillräcklig just nu.",
  "Det är okej att växa långsamt.",
  "Du är tillräcklig precis nu.",
  "Du lär dig mer för varje dag.",
  "Du är inte ensam om att känna så.",
  "Du är okej även när det tar tid.",
  "Du är värd att känna dig trygg.",
  "Du är mer än det du klarar just nu.",
  "Alla gör misstag ibland.",
  "Det är okej att börja om.",
  "Du är tillräcklig även när du är osäker.",
  "Det är okej att inte orka hela tiden.",
  "Alla har sina svåra stunder.",
  "Det är okej att känna sig osäker.",
  "Du lär dig mer än du tror.",
  "Du är okej som du är.",
  "Du är okej även när du inte förstår allt.",
  "Du duger utan att prestera.",
  "Det är okej att vara nyfiken.",
  "Du duger som du är.",
  "Du gör framsteg på ditt sätt.",
  "Du duger, precis som du är.",
  "Du är värd att ta det lugnt.",
  "Du gör framsteg även i stillhet.",
  "Det är okej att ta nya försök.",
  "Du behöver inte förklara allt.",
  "Du lär dig även när du tänker.",
  "Det är okej att känna sig stilla.",
  "Du är okej även när du ändrar dig.",
  "Du duger även utan plan.",
  "Du är okej även när du reagerar starkt.",
  "Du duger även med hela ditt hjärta.",
  "Du behöver inte skynda framåt.",
  "Du duger även i pausen.",
  "Du behöver inte pressa dig.",
  "Du duger även när du skyddar dig.",
  "Du behöver inte lösa allt nu.",
  "Du duger även mitt i processen.",
  "Du är okej även när du längtar.",
  "Du är okej även när du söker din plats.",
  "Du duger även när du letar.",
  "Du är okej även när du utforskar.",
  "Du kan göra detta.",
  "Du är kapabel.",
  "Du kan fortsätta i din takt.",
  "Du kan bli tryggare med tiden.",
  "Du är lärande, inte misslyckad.",
  "Du har redan visat mod.",
  "Du har viljan att lära.",
  "Du är inte fast, du rör dig.",
  "Du kan växa i det här.",
  "Du är på väg att bli tryggare.",
  "Du kan hantera det som kommer.",
  "Du kan bli stolt över dig själv.",
  "Du har redan styrka inom dig.",
  "Du kan växa av det här.",
  "Du har mod att fortsätta.",
  "Du kan fortsätta försöka.",
  "Du är på rätt väg, även om den är krokig.",
  "Du kan fortsätta växa.",
  "Du är modig som inte ger upp.",
  "Du kan bli tryggare med varje dag.",
  "Du lär dig lite mer varje dag.",
  "Du är duktig på att försöka.",
  "Du kan öva och bli säkrare.",
  "Du är modig som försöker igen.",
  "Du kan ta en paus och fortsätta sen.",
  "Du gör något bra när du försöker.",
  "Du är inte ensam om att kämpa.",
  "Du är stark på ditt sätt.",
  "Du är modig som inte ger upp.",
  "Du kan fortsätta försöka.",
  "Du är redo att försöka igen.",
  "Du kan tro lite mer på dig själv.",
  "Du har mod att fortsätta.",
  "Du kan känna stolthet över din resa.",
  "Du är modig som försöker.",
  "Du kan känna tillit till dig själv.",
  "Du är redo att ta nästa steg.",
  "Du kan känna hopp om framtiden.",
  "Du har kraft att utvecklas.",
  "Du klarar mer än du tror."
],
  [
  "Alla lär sig i sin egen takt.",
  "Du är inte ensam om att kämpa.",
  "Alla har bra och dåliga dagar.",
  "Du är tillräcklig.",
  "Det är okej att inte förstå direkt.",
  "Du är okej även när du gör fel.",
  "Du lär dig i din takt.",
  "Det är okej att ta det lugnt.",
  "Du har rätt att ta plats.",
  "Det är okej att vara mänsklig.",
  "Du har rätt att känna det du känner.",
  "Du klarar mer än du tror.",
  "Du räcker till.",
  "Du är värd att bli lyssnad på.",
  "Ingen kan allt från början.",
  "Det är okej att ta ett steg i taget.",
  "Du är modig som fortsätter.",
  "Du är okej, punkt.",
  "Du lär dig, och det är bra.",
  "Ingen är perfekt. Du lär dig och det är helt okej.",
  "Det är okej att vara trött ibland.",
  "Det är okej att inte ha alla svar.",
  "Det är okej att göra fel och försöka igen.",
  "Alla lär sig på sitt sätt.",
  "Det är okej att inte förstå direkt.",
  "Du duger som du är.",
  "Du är inte sämre för att du övar.",
  "Du är okej även idag.",
  "Det är okej att känna sig ledsen ibland.",
  "Du duger ändå.",
  "Du är värd vänlighet.",
  "Du duger precis nu.",
  "Det är okej att ta det lugnt.",
  "Du behöver inte vara bäst.",
  "Alla börjar någonstans.",
  "Du är värd tålamod.",
  "Du är okej även när du lär dig.",
  "Du är okej, punkt.",
  "Alla lär sig olika.",
  "Ingen är perfekt. Du lär dig och det är helt okej.",
  "Det är okej att inte förstå idag.",
  "Du är okej även när du tvivlar mycket.",
  "Du växer även när det är tyst.",
  "Du är okej även när du bara är.",
  "Du är okej även när du inte orkar prata.",
  "Du duger även i tystnad.",
  "Det är okej att inte veta vad du vill.",
  "Du är okej även när allt känns oklart.",
  "Du behöver inte dämpa dig för att duga.",
  "Du är okej även när du känner allt.",
  "Du är okej även när du står still.",
  "Du är okej även mellan stegen.",
  "Du är okej även när du tvekar länge.",
  "Du är okej även när du väljer dig själv.",
  "Du är okej även utan lösning.",
  "Du är okej även när det pågår.",
  "Det är okej att önska mer.",
  "Du duger även på vägen dit.",
  "Du är okej även i osäkerhet.",
  "Du lär dig, och det får ta tid.",
  "Du har förmåga att växa.",
  "Du har kraft inom dig.",
  "Du har det som krävs.",
  "Du är modig som försöker.",
  "Du kan resa dig igen.",
  "Du är stark nog.",
  "Du är kapabel att förändras.",
  "Du kan ta dig igenom detta.",
  "Du har kontroll över dina steg.",
  "Du kan fortsätta, även långsamt.",
  "Du har förmågan att anpassa dig.",
  "Du har kraft att fortsätta.",
  "Du kan utvecklas i din takt.",
  "Du har redan kommit en bit.",
  "Du kan klara mer än igår.",
  "Du har det som behövs inom dig.",
  "Du kan ta dig igenom detta steg.",
  "Du har redan styrkan du behöver.",
  "Du kan fortsätta även när det känns osäkert.",
  "Du gör framsteg, och det är bra.",
  "Du kan vara modig även om du är rädd.",
  "Du kan lära dig nya saker.",
  "Du klarar svåra saker.",
  "Du kan bli bättre med tiden.",
  "Du är stark även när du är trött.",
  "Du är värd att tro på.",
  "Du kan växa av det här.",
  "Du kan fortsätta framåt.",
  "Du kan lära dig av varje försök.",
  "Du är stark nog.",
  "Du kan klara detta i din takt.",
  "Du gör något bra för dig själv.",
  "Du kan klara nästa steg också.",
  "Du är på rätt väg.",
  "Du kan göra framsteg.",
  "Du är stark nog att fortsätta.",
  "Du kan klara mer än du tror.",
  "Du gör ditt bästa.",
  "Du kan klara detta steg.",
  "Du klarar det här."
],
];

let categoryIndex = 0;
let roundIndex = 0;

const quoteEl = document.getElementById("quote");
const nextBtn = document.getElementById("next");

function showNext() {
  const sentence = categories[categoryIndex][roundIndex];
  quoteEl.textContent = sentence;

  categoryIndex++;

  if (categoryIndex >= categories.length) {
    categoryIndex = 0;
    roundIndex++;

    if (roundIndex >= categories[0].length) {
      roundIndex = 0;
    }
  }
}

nextBtn.addEventListener("click", showNext);
